#ifndef SHADERTYPE_HPP
#define SHADERTYPE_HPP

enum ShaderType
{
    RANDOM_SHADER,
    POSITION_SHADER,
    NORMAL_SHADER,
    LAMBERT_SHADER,
    PHONG_SHADER,
    TEXTURE_SHADER,
    COMBINED_SHADER
};

#endif // SHADERTYPE_HPP
